app:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  sender_email: "nate@gmail.com"
  base_url: "foo.bar@google.com"
  auth_token: "my-secret-token"
